[package]
name = "black_sense_core"
version = "0.1.0"
edition = "2021"

[lib]
# Указываем путь вручную, так как по стандарту Rust ищет src/lib.rs, 
# а у нас файл называется main.rs и лежит в корне папки core/
path = "main.rs" 
# cdylib означает компиляцию в динамическую C-библиотеку (обязательно для WASM)
crate-type = ["cdylib"] 

# Настройки для экстремального сжатия итогового .wasm файла
[profile.release]
opt-level = "z"     # Оптимизировать под минимальный размер файла
lto = true          # Включить Link Time Optimization
strip = true        # Вырезать все отладочные символы (снижает вес в разы)
codegen-units = 1   # Максимальная оптимизация (собирается чуть дольше, но код быстрее)
